mysqldb:
  image: mysql:5.7
  env_file: ./config/mysql.env.secret
nginx:
   image: nginx
   restart: always
   volumes:
      - .:/home/TolaActivity
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/activity.toladata.io/fullchain.pem:/etc/letsencrypt/live/activity.toladata.io/fullchain.pem
      - /etc/letsencrypt/live/activity.toladata.io/privkey.pem:/etc/letsencrypt/live/activity.toladata.io/privkey.pem
   ports:
      - "80:80"
      - "443:443"
   links:
      - tola
tola:
   build: .
   command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
   volumes:
       - .:/code
   expose:
       - "8000"
   links:
       - mysqldb
